language: python

python:
  - 3.7

install:
  - pip install -r requirements.txt

before_script:
  - python manage.py migrate

script:
  - black --check .
  - flake8 .
  - coverage run --source=mysite_swe1_app,polls manage.py test

after_script:
  - coveralls

deploy:
  provider: elasticbeanstalk
  access_key_id:
    secure: "lpjWO34pURB7pt3cOlCVA5zobzeULP/k7w98s1GqeNSbZb0KHcuM/A00cMqDDP+c2mezV5uBKymcWf+fdgjpMQz35EtVvypZgsqK17h285qBWI2TQo6BhSi/rWcA2w1a1HSNOK36QWeTi+QgYztZbIrGRU7PdMo6VvySvaM2kD2RpTxQmZiS0iHveZRsG4C1V/uSswx1hwD1wURPL6BxOf0nETN0Z8Q+sI1QVcrozf2eP+JRoW9uumpfDm3tDhry+I9094iY2B9qgGspl7HqTwD0ATD7SJdcjlPA0SapNwiWQHyR/v5KyVJPLIIpzqWP0OfCB8scwr+uURNgkbLTBgRgf8/jRECLYkRitcMgGb/iljNFunDoXtbt9hj2doTy0tlBl8Y8B03Idp7OKPuN4uBg8T8n6e1u1csC9dOIWswj1bpUzefB24pswaQiiqFW2a9gn2OAxHsOJ3XSi/wxdLztBadJKGMj4XbE54gPD7jdP5mCfngZ54rbzDpPLqdSe5zep4JS2VDWf/8iBeJLdjXDvcfENIXVny7rwoYatCzKmSR/Mo3o5r4NoUHTsTB4ENqzolL6FkWpxKJnBiXnu2QSW/os44aJZFOVFBTCOv4uYJygYVf6szHg0vRwXp5xQDHVzbTUmP5fFwllPZu9gDAkdPK5ITveiqvvLeqgHcI="
  secret_access_key:
    secure: "I7532U7J4PtrQCr55/Deeki2gWc6S42rlyemEXVshlibljL0SrFHv7SraEpzoJ2YZaI8acqfwt9NADjjh+XYYqJo7yFlv8dhW6TnqSarwiXtCefO/aiNjZPZh7ab9Uwy4gTNv9V2w78aQ4XWqG9OQyGhEFBkeLDkcQaagM7TEAA8FpfssgQl1945FMlNz/ith6NlCs2lXNYfEB+PVrD2cPnIKm08ttOOVCNMf1/Bq63sDnORZbidaKMErX/KrmI9pfWsiuOKMamggckgMBmZS/7OtKmxciCCOjsSAc5rJ/AjVvu07eEhCqgPjgEp6yR+7pyWHfnQv97AwK1IBRfzp9jB0XdpnxGFW5ODF22Dwxcd5xV8opC9BY5xX38kUSScihWUHj63Rt9MulMCNRCM0oFklL7j1AiAL6uctsVZ6godLWrC8HD465DMOziROuEy/ncxPi2gWprFwacYGPHm15FysJZ7nVyWH+uCpBM4FwwqeVj1RoZ5bKnZi1yVdaQIsdMdCKJWtz6OHUeB1+hg9n1UuLzv+MGvMr7r4YGpIjRbUBa3LdR6G9NRRsX91ahNyCiYr3pwnQ49M2K9aw3bAWROVHgSfTvgBtPKnwqQxj/199MOjybShIokeDn6PPk3hBM2VcXQqQNvMAg3d63JeEVPPbk2WdMApJ5uMFp7bWA="
  region: "us-west-2"
  app: "mysite-eb"
  env: "django-mysite-env"
  bucket_name: "elasticbeanstalk-us-west-2-733181889942"

